# Generated by Django 3.2 on 2022-08-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
