# Generated by Django 3.2 on 2022-08-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
